fdc_status_or_cmd=$fcf8
fdc_track=$fcf9
fdc_sector=$fcfa
fdc_data=$fcfb
fdc_control=$fcfc
ram_paging_msb=$fcfe
ram_paging_lsb=$fcff

osfile=$ffdd
osargs=$ffda
osbget=$ffd7
osbput=$ffd4
osgbpb=$ffd1
osfind=$ffce
fscv=$21e
osrdch=$ffe0
osasci=$ffe3
oswrch=$ffee
osword=$fff1
osbyte=$fff4
oscli=$fff7
gsinit=$ffc2
gsread=$ffc5

chosfile=$9124
chosargs=$a854
chosbget=$ac38
chosbput=$afb2
chosgbpb=$b0d9
chosfind=$9d62

svc_02_private_workspace_claim=$99b9